### ISSUE TITLE
禁止收藏时自动订阅合集

### ISSUE THREAD

**Issue by YuZhangWang** [zjns/BiliRoamingX#10]
### 原因

> 这个问题我看好几个版本都没有加上去，所以来提一个需求，B站有一个合集的功能，相关的一系列视频都放在同一个合集

![图片](https://github.com/zjns/BiliRoamingX/assets/65295250/933c479e-caba-48c5-8395-ad18b45267ce)

> 在我收藏合集中某一个视频的时候，手机端会在收藏界面的最上方，自动勾选订阅这整一个合集，而这并不是我所需要的

![IMG_20230512_073110](https://github.com/zjns/BiliRoamingX/assets/65295250/1aaa786c-443d-4660-b41a-369ca6721642)

> 我需要的是，在我收藏某个视频的时候，不会自动勾选订阅这整一个合集，当我觉得我需要订阅整一个合集的时候，我希望只通过点击合集上方的订阅来实现

![IMG_20230512_074854](https://github.com/zjns/BiliRoamingX/assets/65295250/130a6b66-cc1b-431e-9ca3-d350c450b31e)

### 功能简述

在收藏时，禁止自动勾选上方的订阅合集

### 功能逻辑

在漫游设置中，杂项最后面，添加一个名为“禁止收藏时自动订阅合集”的选项，并且后面加上相同的按钮，用户勾选上该按钮，就能实现该需求

### 实现参考

在最近更新的1.6.10.r1307版本中，我在杂项最后看到了“禁止自动转到动态”这个功能，和我上面提出想添加功能，其实是差不多的，在进行某一行为的时候，把原本会自动勾选的选项给取消

**Comment by YuZhangWang** [comment]
在禁止自动订阅合集中，描述忘记改成这个功能的描述了
![IMG_20230514_163440](https://github.com/zjns/BiliRoamingX/assets/65295250/88fc112e-f210-432f-9238-e1be9d2b3cbc)

**Comment by zjns** [comment]
下个版本修复更正。
