### ISSUE TITLE
[Feature] 取消动态页合集关注按钮

### ISSUE THREAD

**Issue by YuZhangWang** [zjns/BiliRoamingX#11]
### 原因

原来订阅一个合集的时候，动态页面更新时，是没有这个按钮的，就和关注UP主，直接更新的视频一样
上面是订阅的合集更新时展示情况，下面是关注UP主更新时展示情况
![IMG_20230514_163824](https://github.com/zjns/BiliRoamingX/assets/65295250/1eb8884f-8a32-4f7c-8544-17936fd91092)

合集这个功能很好，因为我可能只喜欢某个UP主特定的那些视频，比如一个人工智能UP主，他的编程视频我很喜欢，那么那些什么不要笑挑战，做饭视频，生活视频我就不喜欢看，这个视频，正好他把他编程相关放在一个合集中，我就只需要订阅这个合集就行了，不用关注他，这样在这些视频中，也能给他添加浏览量；或者，影视区UP主，他讲的某个电视剧或者某种类型电影我很喜欢，但是其他的无感，我就可以只关注这些合集内容，避免其他不需要的内容。那么，既然我订阅合集，单纯只是为了这个合集里面的内容，不是这个UP主本身，那么现在在合集更新的时候，加上关注按钮，引导我去关注这个UP主，让我接收到我不想收到的内容，就完全违背了我订阅这个合集时的想法。所以需要让这个关注按钮消失

### 功能简述

在动态中，关注的合集更新时，这个更新视频右上角的关注按钮消失即可

### 功能逻辑

直接移除或者屏蔽，可以放在净化动态和导入自制主题中间，这一部分都是属于移除或者屏蔽功能的

### 实现参考

这个功能，和漫游设置中，和移除视频下方xxx，移除视频xxx，屏蔽xxx这些功能实现，本质上是差不多的，都是让这个东西看不到就行

**Comment by zjns** [comment]
那么大的卡片又不会误触，不点不就行了。

**Comment by YuZhangWang** [comment]
> 那么大的卡片又不会误触，不点不就行了。

这个和隐藏评论关注按钮一样，也经常会误触到的，尤其是合集比较多的时候，就和评论区的关注按钮一样，刷着刷着就会点到了
