### ISSUE TITLE
优化建议

### ISSUE THREAD

**Issue by Lion-hk** [zjns/BiliRoamingX#14]
### 原因

看不清晰.

### 功能简述

模块黑暗主题下，已启用的按钮圆圈不够清晰，尤其是白天或灯光反光下。
而且与黑暗主题色太过于接近了，浏览选项时，很难区分哪些是启用类型哪些是进入勾选类型，会导致误触。
在我的系统去蓝光模式下基本上看不见圆圈，所以建议优化图片颜色以便于区别。或者增加边框，幽蓝色的边框兴许很酷！
这个优化也推荐丢于BiliRoaming中吧
1.16.11功能很棒，非常谢谢制作分享！

### 功能逻辑

替换图片

**Comment by zjns** [comment]
这个问题确实存在，但貌似开启深色模式跟随系统后基本上就没这问题了。
