### ISSUE TITLE
[Feature] 便捷缓存下载

### ISSUE THREAD

**Issue by lrln** [zjns/BiliRoamingX#2]
### 原因

不想快进的时候卡顿，经常缓存观看。
但是b站经常点击缓存麻烦

### 功能简述

希望吧缓存的优先级往上提一提。
比如再动态界面，视频右上角点击三个点，在稍后再看上方有缓存按钮。

### 功能逻辑

动态界面点击三个点添加到稍后再看时，上面有缓存
首页视频卡片右下角三个点，不单单有反馈，我不想看，还有缓存。
稍后再看界面点击右上角三个点可以批量缓存。

555，github问过原作者了，他说不搞，555

**Comment by zjns** [comment]
麻烦，不是简单页面加个按钮的事。
