### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by XJChenYang** [zjns/BiliRoamingX#3]
### 问题描述

最新版本自动点赞好像失效了

### 复现步骤

正常使用

### 预期行为

自动点赞

### 实际行为

自动点赞失效

### 安卓版本

12

### 哔哩漫游版本

1.6.6_T22101915

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.2.0

### 使用的框架和版本

Lspatch 0.4-337

### 其他

本身功能

### 日志

[log.txt](https://github.com/zjns/BiliRoamingX/files/9819870/log.txt)

**Comment by zjns** [comment]
上游已经修复。
