### ISSUE TITLE
[Feature] 自定义播放速度列表

### ISSUE THREAD

**Issue by My-Responsitories** [zjns/BiliRoamingX#5]
### 原因

上游似乎不再考虑添加该功能. [v1.4.5](https://github.com/yujincheng08/BiliRoaming/releases/tag/v1.4.5)的自定义播放速度列表在 哔哩哔哩v6.45.0 (更高版本漫游启动报name == null, 无法再测试了) 全屏播放后右上角竖着的三个点进入仍可以修改播放速度, 只是显示有问题, 实测确实是修改后的倍速

### 功能简述

自定义默认的6个倍速选项

### 功能逻辑

修改全屏播放后右上角竖着的三个点的播放速度

### 实现参考

https://github.com/yujincheng08/BiliRoaming/pull/98

**Comment by zjns** [comment]
个人没这需求，倍速都很少用，不想浪费时间折腾
