### ISSUE TITLE
添加长按倍速播放与报小bug

### ISSUE THREAD

**Issue by Lion-hk** [zjns/BiliRoamingX#8]
### 原因

两年前用过嵌入版的apk，自从封了一批以后没再找到过（- -），这个月才找见biliroaming和x，回到组织。
之前用过修改长按倍速播放的，1.7倍可以听到视频无论新闻或者vlog的讲话，2倍以上听不见。所以想请求大佬加回来这个功能。

报告几个不重要的bug，，修改倍速列表里有0.8、0.9倍速，点击0.8或0.9会显示两个都是蓝色，点击其它倍速则独自一个蓝色框。
自定义【我的】页面无论丢到左侧头像还是原处，我设置的保留【听视频】【钱包】都不显示，安卓8未root用的太极分装哔哩与x，收藏和历史等主要图标功能保留均正常。其它图标未测，需要其它测试帮助大佬可以说明。

### 功能简述

修改长按倍速播放，因可能存在视频区的个人差异，推荐可以自定义修改。
我看新闻和vlog以前用1.7被就很舒心。

### 功能逻辑

漫游x里自定义

### 实现参考

无

**Comment by Lion-hk** [comment]
哔哩哔哩7.24.0版本
哔哩漫游x1.6.10版本

**Comment by Lion-hk** [comment]
已star

**Comment by zjns** [comment]
倍速列表倍速间差值不能小于0.15还是好多，记不太清了，不然就会被APP判定为两个倍速一样；自定义我的页面想要保留的项对应的分组标题项也必须保留，不然不能显示。

**Comment by Lion-hk** [comment]
@zjns 
几时更新漫游x独立版1.6.11
集成版本安卓8无法安上

**Comment by zjns** [comment]
> @zjns 几时更新漫游x独立版1.6.11 集成版本安卓8无法安上

https://t.me/bb_show
