### ISSUE TITLE
[Bug] 竖屏视频没有全屏选项，只有进入竖屏选项，导致竖屏视频只能在竖屏模式下看

### ISSUE THREAD

**Issue by Vinnry** [zjns/BiliRoamingX#9]
### 问题描述

[Bug] 竖屏视频没有全屏选项，只有进入竖屏选项，导致竖屏视频只能在竖屏模式下看

### 复现步骤

漫游里面打开  取代竖版影片为正常影片
但是看竖版影片还是处于竖版模式

### 预期行为

看竖版视频应该像横版视频一样的播放逻辑而不进入竖版影片模式，而不是像短视频那样的逻辑

### 实际行为

看竖版影片实际上没有取代竖版影片模式，还是进入了竖版影片模式

### 截图或录屏

![Screenshot_2023-05-11-21-46-36-703_tv danmaku bili](https://github.com/zjns/BiliRoamingX/assets/130174586/b349ca31-ea26-4d3c-adcc-715c054b6ff4)
![IMG_20230511_214740](https://github.com/zjns/BiliRoamingX/assets/130174586/89ad2bcb-3891-4925-b307-986795209b18)

### 安卓版本

9

### 哔哩漫游版本

1.6.10.r1297

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.28

### 使用的框架和版本

B站自带漫游没有框架

### 日志

[log.txt](https://github.com/zjns/BiliRoamingX/files/11452915/log.txt)

**Comment by zjns** [comment]
APP播放设置有个竖屏相关的开关关了看看

**Comment by Vinnry** [comment]
关掉了，然后搞定了。。。。。。多谢
